title: Gerald Britton, Pluralsight author
email: gerald.britton@gmail.com
description: Easy access to my courses on Pluralsight.com
# baseurl: "gbritton1"
# url: https://gbritton1.github.io/
twitter_username: GeraldBritton
github_username: gbritton1

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal